import assert from 'node:assert/strict';
import { appendDimension, availableLineDimensionKinds, chooseLineDimensionKind, createLineDimension, deleteDimension, deleteEntityWithDependentDimensions, formatLinearDimension, measureDimension, parseLinearDimension, resolveDrawingPointReference } from '../.test-build/drawing-dimension/drawingDimension.js';
import { createDrawingDocumentV1, createDrawingDocumentV2, migrateDrawingDocument } from '../.test-build/drawing-dimension/drawingTypes.js';

const line = { id: 'line-17', type: 'line', start: { x: 0, y: 0 }, end: { x: 100, y: 50 } };
assert.equal(measureDimension('ALIGNED_DISTANCE', line.start, line.end), Math.hypot(100, 50));
assert.equal(measureDimension('HORIZONTAL_DISTANCE', line.start, line.end), 100);
assert.equal(measureDimension('VERTICAL_DISTANCE', line.start, line.end), 50);
const dimension = createLineDimension(line, 'ALIGNED_DISTANCE', { x: 40, y: 80 }, 'dimension-stable');
assert.equal(dimension.id, 'dimension-stable');
assert.deepEqual(dimension.references, [{ kind: 'point', entityId: 'line-17', point: 'start' }, { kind: 'point', entityId: 'line-17', point: 'end' }]);
assert.equal('x' in dimension.references[0], false);
assert.deepEqual(availableLineDimensionKinds({ ...line, end: { x: 100, y: 0 } }), ['ALIGNED_DISTANCE', 'VERTICAL_DISTANCE']);
assert.deepEqual(availableLineDimensionKinds({ ...line, end: { x: 0, y: 100 } }), ['ALIGNED_DISTANCE', 'HORIZONTAL_DISTANCE']);
assert.equal(chooseLineDimensionKind(line, { x: 50, y: 100 }), chooseLineDimensionKind(line, { x: 50, y: 100 }));
assert.equal(chooseLineDimensionKind(line, { x: 50, y: 100 }, chooseLineDimensionKind(line, { x: 50, y: 100 })), chooseLineDimensionKind(line, { x: 50, y: 100 }));
for (const [value, expected] of [[120, '120 mm'], [120.0, '120 mm'], [120.5, '120.5 mm'], [120.125, '120.125 mm'], [0, '0 mm']]) assert.equal(formatLinearDimension(value), expected);
for (const [text, expected] of [['120',120],['120mm',120],['120 mm',120],['120.5',120.5],['0',0],['0.000',0]]) assert.equal(parseLinearDimension(text), expected);
for (const text of ['-1','NaN','Infinity','word','2cm','1.2.3']) assert.equal(parseLinearDimension(text), null);
let document = createDrawingDocumentV2();
document = { ...document, sketches: { ...document.sketches, 'sketch-1': { ...document.sketches['sketch-1'], entities: { 'line-17': line }, entityOrder: ['line-17'] } } };
const placed = appendDimension(document, dimension);
assert.equal(placed.sketches['sketch-1'].dimensionOrder[0], 'dimension-stable');
assert.deepEqual(resolveDrawingPointReference(placed.sketches['sketch-1'], dimension.references[1]), line.end);
assert.deepEqual(deleteDimension(placed, dimension.id).sketches['sketch-1'].entities['line-17'], line);
const cascaded = deleteEntityWithDependentDimensions(placed, line.id);
assert.equal(cascaded.sketches['sketch-1'].dimensions[dimension.id], undefined);
assert.equal(migrateDrawingDocument(createDrawingDocumentV1()).schemaVersion, 2);
assert.deepEqual(migrateDrawingDocument(createDrawingDocumentV1()).sketches['sketch-1'].dimensionOrder, []);
console.log('drawing dimension foundation tests passed');
