import assert from 'node:assert/strict';
import { appendDimension, classifyNewDimensionRole, createPointToLineDimension, derivePointToLineAnnotationGeometry, displayedDimensionMeasurement, measurePointToLine, pointToLineDimensionOffset } from '../.test-build/drawing-point-to-line/drawingDimension.js';
import { resolvePointToLineMovementIntent, solveDrawingDimensionEdit, verifyDrawingDrivingDimensions } from '../.test-build/drawing-point-to-line/drawingConstraintSolver.js';
const point = (pointId) => ({ kind: 'sketchPoint', pointId });
const entity = (entityId) => ({ kind: 'entity', entityId });
const base = (p = { x: 5, y: 5 }, a = { x: 0, y: 0 }, b = { x: 10, y: 0 }) => ({ schemaVersion: 2, unit: 'mm', activeSketchId: 's', sketchOrder: ['s'], sketches: { s: { id: 's', name: 'Sketch', points: { p: { id: 'p', ...p }, a: { id: 'a', ...a }, b: { id: 'b', ...b }, q: { id: 'q', x: p.x - 3, y: p.y } }, entities: { l: { id: 'l', type: 'line', startPointId: 'a', endPointId: 'b' }, incident: { id: 'incident', type: 'line', startPointId: 'q', endPointId: 'p' } }, entityOrder: ['l', 'incident'], dimensions: {}, dimensionOrder: [] } } });
const line = (doc) => ({ ...doc.sketches.s.entities.l, start: doc.sketches.s.points.a, end: doc.sketches.s.points.b });
const make = (doc, preference, id = 'd') => createPointToLineDimension(point('p'), entity('l'), doc.sketches.s.points.p, line(doc), preference, { x: 4, y: 8 }, id);
assert.equal(measurePointToLine({ x: 2, y: 7 }, { ...line(base()), start: { x: 0, y: 0 }, end: { x: 10, y: 0 } }), 7);
assert.equal(measurePointToLine({ x: 7, y: 2 }, { ...line(base()), start: { x: 0, y: 0 }, end: { x: 0, y: 10 } }), 7);
assert.ok(Math.abs(measurePointToLine({ x: 0, y: 2 }, { ...line(base()), start: { x: 0, y: 0 }, end: { x: 2, y: 2 } }) - Math.SQRT2) < 1e-12);
assert.equal(measurePointToLine({ x: 5, y: 0 }, line(base({ x: 5, y: 0 }))), 0);
assert.equal(measurePointToLine({ x: 1, y: 1 }, { ...line(base()), start: { x: 0, y: 0 }, end: { x: 0, y: 0 } }), null);
const diagonal = { ...line(base()), start: { x: 0, y: 0 }, end: { x: 8, y: 6 } };
const annotationPoint = { x: 1, y: 9 };
const placementCursor = { x: 7, y: 8 };
const annotationOffset = pointToLineDimensionOffset(annotationPoint, diagonal, placementCursor);
const annotation = derivePointToLineAnnotationGeometry(annotationPoint, diagonal, annotationOffset);
assert.ok(annotation);
assert.equal(Object.values(base().sketches.s.points).some(({ x, y }) => Math.abs(x - annotation.sourceA.x) < 1e-12 && Math.abs(y - annotation.sourceA.y) < 1e-12), false, 'derived projection Q is not a persisted SketchPoint');
const tangent = { x: diagonal.end.x - diagonal.start.x, y: diagonal.end.y - diagonal.start.y };
const main = { x: annotation.b.x - annotation.a.x, y: annotation.b.y - annotation.a.y };
const witnessA = { x: annotation.a.x - annotation.sourceA.x, y: annotation.a.y - annotation.sourceA.y };
const witnessB = { x: annotation.b.x - annotation.sourceB.x, y: annotation.b.y - annotation.sourceB.y };
assert.ok(Math.abs(main.x * tangent.x + main.y * tangent.y) < 1e-10, 'diagonal main arrow/value vector is perpendicular to the selected line');
assert.ok(Math.abs(main.x * tangent.y - main.y * tangent.x) > 1e-6, 'main arrow/value vector is not parallel to the selected line');
assert.ok(Math.abs(witnessA.x * tangent.y - witnessA.y * tangent.x) < 1e-10, 'line-side witness follows the tangent');
assert.ok(Math.abs(witnessB.x * tangent.y - witnessB.y * tangent.x) < 1e-10, 'point-side witness follows the tangent');
assert.ok(Math.abs(Math.hypot(main.x, main.y) - measurePointToLine(annotationPoint, diagonal)) < 1e-10, 'main segment carries the measured perpendicular value');
assert.ok(Math.abs(annotation.sourceA.x - 4.96) < 1e-10 && Math.abs(annotation.sourceA.y - 3.72) < 1e-10, 'line-side witness traces to perpendicular projection Q on the infinite line');
assert.equal(annotation.lineExtension, undefined, 'Q inside the finite segment visibly joins the model Line directly');
const farAnnotation = derivePointToLineAnnotationGeometry(annotationPoint, diagonal, 120);
assert.ok(farAnnotation && Math.hypot(farAnnotation.a.x - farAnnotation.sourceA.x, farAnnotation.a.y - farAnnotation.sourceA.y) > 100, 'far placement retains its line-side witness back to Q');
const outsideAnnotation = derivePointToLineAnnotationGeometry({ x: 15, y: 10 }, diagonal, 120);
assert.deepEqual(outsideAnnotation.lineExtension.start, diagonal.end, 'outside-segment lineage starts at the nearest visible Line endpoint');
assert.deepEqual(outsideAnnotation.lineExtension.end, outsideAnnotation.sourceA, 'outside-segment lineage reaches Q without a visual gap');
assert.ok(Math.hypot(outsideAnnotation.lineExtension.end.x - (outsideAnnotation.a.x - 120 * tangent.x / 10), outsideAnnotation.lineExtension.end.y - (outsideAnnotation.a.y - 120 * tangent.y / 10)) < 1e-12, 'distant diagonal witness and derived extension share the same Q');
for (const preference of ['point', 'line']) { const doc = base(), d = make(doc, preference); assert.equal(d.kind, 'POINT_TO_LINE_DISTANCE'); assert.equal(d.movementPreference, preference); }
let doc = base(), first = make(doc, 'point', 'first'); doc = appendDimension(doc, first); const reverseIntent = make(doc, 'line', 'reverse'); assert.deepEqual(classifyNewDimensionRole(doc.sketches.s, reverseIntent), { role: 'reference', reason: 'duplicate' }); assert.equal(appendDimension(doc, reverseIntent), doc);
const pointFirstIntent = resolvePointToLineMovementIntent(doc.sketches.s, doc.sketches.s.dimensions.first);
assert.equal(pointFirstIntent.preferred.kind, 'ISOLATED_LINE_RIGID_TRANSLATION'); assert.deepEqual(pointFirstIntent.preferred.lineIds, ['l']); assert.deepEqual(pointFirstIntent.preferred.pointIds, ['a', 'b']);
let solved = solveDrawingDimensionEdit({ document: doc, dimensionId: 'first', targetValue: 8 }); assert.equal(solved.ok, true); assert.deepEqual(solved.document.sketches.s.points.p, doc.sketches.s.points.p); assert.ok(Math.abs(solved.document.sketches.s.points.a.y + 3) < 1e-7); assert.ok(Math.abs(solved.document.sketches.s.points.b.y + 3) < 1e-7); assert.equal(solved.document.sketches.s.entities.incident.endPointId, 'p');
const pointFirstSolved = solved.document;
doc = base(); doc = appendDimension(doc, make(doc, 'line')); solved = solveDrawingDimensionEdit({ document: doc, dimensionId: 'd', targetValue: 8 }); assert.equal(solved.ok, true); const s = solved.document.sketches.s; assert.deepEqual(s.points.p, doc.sketches.s.points.p); assert.ok(Math.abs(s.points.a.y + 3) < 1e-7 && Math.abs(s.points.b.y + 3) < 1e-7); assert.ok(Math.abs(Math.hypot(s.points.b.x - s.points.a.x, s.points.b.y - s.points.a.y) - 10) < 1e-7);
assert.deepEqual(resolvePointToLineMovementIntent(doc.sketches.s, doc.sketches.s.dimensions.d), pointFirstIntent, 'click order produces identical movement intent');
assert.deepEqual(solved.document.sketches.s.points, pointFirstSolved.sketches.s.points, 'click order produces equivalent final geometry');
const lineSolvedDocument = solved.document;
assert.deepEqual({ x: s.points.a.x - doc.sketches.s.points.a.x, y: s.points.a.y - doc.sketches.s.points.a.y }, { x: s.points.b.x - doc.sketches.s.points.b.x, y: s.points.b.y - doc.sketches.s.points.b.y }, 'Line -> Point moves both endpoints by the identical vector');
solved = solveDrawingDimensionEdit({ document: solved.document, dimensionId: 'd', targetValue: 2 }); assert.equal(solved.ok, true); assert.ok(solved.document.sketches.s.points.a.y < doc.sketches.s.points.p.y, 'same-side edit does not cross the point');
const diagonalLineDoc = base({ x: 3, y: 9 }, { x: 0, y: 0 }, { x: 8, y: 6 });
diagonalLineDoc.sketches.s.dimensions.d = make(diagonalLineDoc, 'line'); diagonalLineDoc.sketches.s.dimensionOrder = ['d'];
solved = solveDrawingDimensionEdit({ document: diagonalLineDoc, dimensionId: 'd', targetValue: 7 }); assert.equal(solved.ok, true);
const diagonalSolved = solved.document.sketches.s;
assert.ok(Math.abs((diagonalSolved.points.a.x - diagonalLineDoc.sketches.s.points.a.x) - (diagonalSolved.points.b.x - diagonalLineDoc.sketches.s.points.b.x)) < 1e-12 && Math.abs((diagonalSolved.points.a.y - diagonalLineDoc.sketches.s.points.a.y) - (diagonalSolved.points.b.y - diagonalLineDoc.sketches.s.points.b.y)) < 1e-12, 'diagonal endpoints receive the same translation vector');
assert.ok(Math.abs(diagonalSolved.points.b.x - diagonalSolved.points.a.x - 8) < 1e-12 && Math.abs(diagonalSolved.points.b.y - diagonalSolved.points.a.y - 6) < 1e-12, 'rigid preferred attempt preserves diagonal line direction and length');
const reverseCreationDoc = base(); reverseCreationDoc.sketches.s.entityOrder = ['incident', 'l']; reverseCreationDoc.sketches.s.dimensions.d = make(reverseCreationDoc, 'point'); reverseCreationDoc.sketches.s.dimensionOrder = ['d'];
assert.deepEqual(resolvePointToLineMovementIntent(reverseCreationDoc.sketches.s, reverseCreationDoc.sketches.s.dimensions.d).preferred.lineIds, ['incident']);
solved = solveDrawingDimensionEdit({ document: reverseCreationDoc, dimensionId: 'd', targetValue: 8 }); assert.equal(solved.ok, true); assert.deepEqual(solved.document.sketches.s.points.a, reverseCreationDoc.sketches.s.points.a); assert.deepEqual(solved.document.sketches.s.points.b, reverseCreationDoc.sketches.s.points.b); assert.deepEqual({ x: solved.document.sketches.s.points.q.x - reverseCreationDoc.sketches.s.points.q.x, y: solved.document.sketches.s.points.q.y - reverseCreationDoc.sketches.s.points.q.y }, { x: solved.document.sketches.s.points.p.x - reverseCreationDoc.sketches.s.points.p.x, y: solved.document.sketches.s.points.p.y - reverseCreationDoc.sketches.s.points.p.y });
const connectedDoc = base(); connectedDoc.sketches.s.entityOrder = ['incident', 'l', 'branch']; connectedDoc.sketches.s.points.r = { id: 'r', x: 0, y: 8 }; connectedDoc.sketches.s.entities.branch = { id: 'branch', type: 'line', startPointId: 'q', endPointId: 'r' }; connectedDoc.sketches.s.dimensions.d = make(connectedDoc, 'line'); connectedDoc.sketches.s.dimensionOrder = ['d'];
const connectedIntent = resolvePointToLineMovementIntent(connectedDoc.sketches.s, connectedDoc.sketches.s.dimensions.d); assert.equal(connectedIntent.preferred.kind, 'ISOLATED_LINE_RIGID_TRANSLATION'); assert.deepEqual(connectedIntent.preferred.lineIds, ['l']); assert.equal(connectedIntent.reason, 'LOWER_TOPOLOGY_COST', 'topology outranks the earlier creation order of the connected figure');
solved = solveDrawingDimensionEdit({ document: connectedDoc, dimensionId: 'd', targetValue: 8 }); assert.equal(solved.ok, true); for (const id of ['p', 'q', 'r']) assert.deepEqual(solved.document.sketches.s.points[id], connectedDoc.sketches.s.points[id], 'connected figure remains stationary'); assert.deepEqual({ x: solved.document.sketches.s.points.a.x - connectedDoc.sketches.s.points.a.x, y: solved.document.sketches.s.points.a.y - connectedDoc.sketches.s.points.a.y }, { x: solved.document.sketches.s.points.b.x - connectedDoc.sketches.s.points.b.x, y: solved.document.sketches.s.points.b.y - connectedDoc.sketches.s.points.b.y }, 'later isolated Line translates rigidly'); assert.equal(solved.document.sketches.s.entities.branch.startPointId, 'q', 'shared topology remains intact'); assert.ok(verifyDrawingDrivingDimensions(solved.document.sketches.s, ['d']));
const connectedCreatedLater = structuredClone(connectedDoc); connectedCreatedLater.sketches.s.entityOrder = ['l', 'incident', 'branch']; assert.deepEqual(resolvePointToLineMovementIntent(connectedCreatedLater.sketches.s, connectedCreatedLater.sketches.s.dimensions.d).preferred.lineIds, ['l'], 'isolated Line also wins when created first');
const fallbackDoc = base();
fallbackDoc.sketches.s.dimensions.d = make(fallbackDoc, 'line');
fallbackDoc.sketches.s.dimensions.lockAHeight = { id: 'lockAHeight', kind: 'VERTICAL_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, point('a')], value: 0, placement: { kind: 'linear', offset: 0 } };
fallbackDoc.sketches.s.dimensionOrder = ['d', 'lockAHeight'];
solved = solveDrawingDimensionEdit({ document: fallbackDoc, dimensionId: 'd', targetValue: 6 }); assert.equal(solved.ok, true, 'generic component fallback solves when rigid translation conflicts');
assert.ok(Math.abs(solved.document.sketches.s.points.a.y) < 1e-7 && verifyDrawingDrivingDimensions(solved.document.sketches.s, ['d', 'lockAHeight']), 'fallback preserves every driving constraint');
const lockedIsolatedDoc = structuredClone(connectedDoc);
lockedIsolatedDoc.sketches.s.dimensions.lockAX = { id: 'lockAX', kind: 'HORIZONTAL_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, point('a')], value: 0, placement: { kind: 'linear', offset: 0 } };
lockedIsolatedDoc.sketches.s.dimensions.lockAY = { id: 'lockAY', kind: 'VERTICAL_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, point('a')], value: 0, placement: { kind: 'linear', offset: 0 } };
lockedIsolatedDoc.sketches.s.dimensions.lockBX = { id: 'lockBX', kind: 'HORIZONTAL_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, point('b')], value: 10, placement: { kind: 'linear', offset: 0 } };
lockedIsolatedDoc.sketches.s.dimensions.lockBY = { id: 'lockBY', kind: 'VERTICAL_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, point('b')], value: 0, placement: { kind: 'linear', offset: 0 } };
lockedIsolatedDoc.sketches.s.dimensionOrder.push('lockAX', 'lockAY', 'lockBX', 'lockBY');
solved = solveDrawingDimensionEdit({ document: lockedIsolatedDoc, dimensionId: 'd', targetValue: 8 }); assert.equal(solved.ok, true, 'connected-side fallback solves when the simpler isolated Line is locked'); assert.deepEqual(solved.document.sketches.s.points.a, lockedIsolatedDoc.sketches.s.points.a); assert.deepEqual(solved.document.sketches.s.points.b, lockedIsolatedDoc.sketches.s.points.b); assert.notDeepEqual(solved.document.sketches.s.points.p, lockedIsolatedDoc.sketches.s.points.p, 'connected figure uses local point DOF'); assert.ok(verifyDrawingDrivingDimensions(solved.document.sketches.s, lockedIsolatedDoc.sketches.s.dimensionOrder));
const twoConnectedDoc = structuredClone(connectedDoc); twoConnectedDoc.sketches.s.points.c = { id: 'c', x: -4, y: 0 }; twoConnectedDoc.sketches.s.entities.lineBranch = { id: 'lineBranch', type: 'line', startPointId: 'a', endPointId: 'c' }; twoConnectedDoc.sketches.s.entityOrder.push('lineBranch');
solved = solveDrawingDimensionEdit({ document: twoConnectedDoc, dimensionId: 'd', targetValue: 8 }); assert.equal(solved.ok, true); assert.deepEqual(solved.document.sketches.s.points.c, twoConnectedDoc.sketches.s.points.c, 'two connected figures use local deformation rather than whole-chain translation'); assert.deepEqual(solved.document.sketches.s.points.q, twoConnectedDoc.sketches.s.points.q); assert.deepEqual(solved.document.sketches.s.points.r, twoConnectedDoc.sketches.s.points.r); assert.notDeepEqual(solved.document.sketches.s.points.p, twoConnectedDoc.sketches.s.points.p, 'only the legitimate local joint/endpoint needs to move'); assert.ok(verifyDrawingDrivingDimensions(solved.document.sketches.s, ['d']));
const originDoc = base({ x: 50, y: 50 }, { x: 0, y: 5 }, { x: 10, y: 5 });
originDoc.sketches.s.dimensions.originDistance = { id: 'originDistance', kind: 'POINT_TO_LINE_DISTANCE', role: 'driving', references: [{ kind: 'datum', datum: 'ORIGIN' }, entity('l')], movementPreference: 'line', value: 5, placement: { kind: 'linear', offset: 0 } };
originDoc.sketches.s.dimensionOrder = ['originDistance'];
solved = solveDrawingDimensionEdit({ document: originDoc, dimensionId: 'originDistance', targetValue: 9 }); assert.equal(solved.ok, true);
const originSolved = solved.document.sketches.s;
assert.deepEqual({ x: originSolved.points.a.x - originDoc.sketches.s.points.a.x, y: originSolved.points.a.y - originDoc.sketches.s.points.a.y }, { x: originSolved.points.b.x - originDoc.sketches.s.points.b.x, y: originSolved.points.b.y - originDoc.sketches.s.points.b.y }, 'Line -> Origin rigidly translates both endpoints');
assert.equal(measurePointToLine({ x: 0, y: 0 }, line(solved.document)), 9);
const originPointOrder = structuredClone(originDoc); originPointOrder.sketches.s.dimensions.originDistance.movementPreference = 'point';
assert.deepEqual(resolvePointToLineMovementIntent(originPointOrder.sketches.s, originPointOrder.sketches.s.dimensions.originDistance), resolvePointToLineMovementIntent(originDoc.sketches.s, originDoc.sketches.s.dimensions.originDistance));
const originPointSolved = solveDrawingDimensionEdit({ document: originPointOrder, dimensionId: 'originDistance', targetValue: 9 }); assert.equal(originPointSolved.ok, true); assert.deepEqual(originPointSolved.document.sketches.s.points, solved.document.sketches.s.points, 'Origin click order does not affect ownership or geometry');
const independentDoc = base(); independentDoc.sketches.s.points.free = { id: 'free', x: 2, y: 4 }; independentDoc.sketches.s.dimensions.freeDistance = { ...make(independentDoc, 'line'), id: 'freeDistance', references: [point('free'), entity('l')] };
const independentIntent = resolvePointToLineMovementIntent(independentDoc.sketches.s, independentDoc.sketches.s.dimensions.freeDistance); assert.equal(independentIntent.preferred.kind, 'INDEPENDENT_POINT', 'pure model resolver prefers a genuinely independent point'); assert.deepEqual(independentIntent.preferred.pointIds, ['free']);
const reference = { ...make(base(), 'point'), role: 'reference', value: 999 }; doc = base(); doc.sketches.s.dimensions.d = reference; doc.sketches.s.dimensionOrder = ['d']; assert.equal(displayedDimensionMeasurement(doc.sketches.s, reference), 5); doc.sketches.s.points.p.y = 9; assert.equal(displayedDimensionMeasurement(doc.sketches.s, reference), 9);
assert.ok(verifyDrawingDrivingDimensions(lineSolvedDocument.sketches.s, ['d']));
console.log('drawing point-to-line dimension tests passed');
